name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xclip libgtk-3-dev libayatana-appindicator3-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: make test
    
    - name: Test with coverage
      run: make test-coverage
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
    
    - name: Build binary
      run: make build
    
    - name: Verify binary exists
      run: ls -la clipboard-manager
    
    - name: Build release package
      run: make dist
    
    - name: Verify release package
      run: ls -la build/clipboard-manager-release.tar.gz build/release/
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: clipboard-manager-linux
        path: clipboard-manager
    
    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: clipboard-manager-release
        path: build/clipboard-manager-release.tar.gz
    
    - name: Upload release directory
      uses: actions/upload-artifact@v4
      with:
        name: clipboard-manager-release-dir
        path: build/release/

  # Artifacts are uploaded for debugging and development
  # Actual releases are handled by the release.yml workflow