name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xclip libgtk-3-dev libayatana-appindicator3-dev
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build binary
      run: go build -o clipboard-manager
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: clipboard-manager-linux
        path: clipboard-manager